// Mock data for development and testing

import { Listing } from "./types";

export const mockListings: Listing[] = [
  {
    id: "listing-1",
    title: "Trek Mountain Bike - Excellent Condition",
    description: "2022 Trek X-Caliber 8, lightly used with upgrades. Perfect for trails and commuting.",
    imageUrl: "https://otesports.com/wp-content/uploads/2025/05/Trek-Marlin-4-2.png",
    distanceMiles: 2.3,
    price: 1200,
    brand: "Trek",
    condition: "like-new",
    confidenceScore: 95,
    fraudStatus: "clear",
  },
  {
    id: "listing-2",
    title: "Giant Road Bike",
    description: "Giant Contend 3, great for road cycling. Minor scratches but mechanically sound.",
    imageUrl: "https://hips.hearstapps.com/hmg-prod/images/giant-tcr-advanced-pro-0-0037-1585580453.jpg?crop=0.889xw:1.00xh;0.0561xw,0&resize=768:*",
    distanceMiles: 5.7,
    price: 850,
    brand: "Giant",
    condition: "used",
    confidenceScore: 88,
    fraudStatus: "clear",
  },
  {
    id: "listing-3",
    title: "Specialized Electric Bike - Brand New",
    description: "Specialized Turbo Vado SL, still in box. Never ridden, unopened packaging.",
    imageUrl: "https://hips.hearstapps.com/hmg-prod/images/specialized-levo-ec-1616455178.jpg?crop=0.726xw:0.819xh;0.155xw,0.0856xh&resize=768:*",
    distanceMiles: 8.2,
    price: 3500,
    brand: "Specialized",
    condition: "new",
    confidenceScore: 99,
    fraudStatus: "clear",
  },
  {
    id: "listing-4",
    title: "Cannondale Hybrid Bike",
    description: "Versatile hybrid bike, great for city and light trails. Well maintained.",
    imageUrl: "https://embed.widencdn.net/img/dorelrl/iizetjwtzy/800px@1x/C21_C31400F_Quick_Disc_4_CMT_3Q.jpg?color=E7F3F8&q=90",
    distanceMiles: 3.1,
    price: 650,
    brand: "Cannondale",
    condition: "like-new",
    confidenceScore: 92,
    fraudStatus: "clear",
  },
  {
    id: "listing-5",
    title: "Trek Cruiser - Comfortable Ride",
    description: "Classic cruiser style, perfect for beach rides and casual cycling.",
    imageUrl: "https://otesports.com/wp-content/uploads/2025/05/Trek-Marlin-4-2.png",
    distanceMiles: 1.8,
    price: 450,
    brand: "Trek",
    condition: "used",
    confidenceScore: 85,
    fraudStatus: "clear",
  },
  {
    id: "listing-6",
    title: "Giant Mountain Bike - Trail Ready",
    description: "Giant Talon 2, suspension fork, disc brakes. Ready for serious trails.",
    imageUrl: "https://mbaction.com/wp-content/uploads/2025/01/M9_Giant_e-copy.jpg",
    distanceMiles: 6.5,
    price: 980,
    brand: "Giant",
    condition: "like-new",
    confidenceScore: 90,
    fraudStatus: "clear",
  },
  {
    id: "listing-7",
    title: "Specialized Road Bike - Racing Edition",
    description: "Specialized Allez Sprint, carbon fiber components. Serious racing bike.",
    imageUrl: "https://www.tobedetermined.cc/journal/2019/2/the-best-bikes-specialized-tarmac-sl6",
    distanceMiles: 12.4,
    price: 2100,
    brand: "Specialized",
    condition: "like-new",
    confidenceScore: 93,
    fraudStatus: "clear",
  },
  {
    id: "listing-8",
    title: "Cannondale Kids Bike",
    description: "Perfect starter bike for kids 6-10 years old. Adjustable seat and training wheels included.",
    imageUrl: "https://images.cdn.europe-west1.gcp.commercetools.com/078b97e9-ed31-4c81-baae-cdd44f3bf3c1/56c2f5b5c9b335faefdd-ss1nzTlP.jpg",
    distanceMiles: 4.2,
    price: 280,
    brand: "Cannondale",
    condition: "used",
    confidenceScore: 87,
    fraudStatus: "clear",
  },
];

export const availableBrands = ["Trek", "Giant", "Specialized", "Cannondale"];

