// Mock data for development and testing

import { Listing } from "./types";

export const mockListings: Listing[] = [
  {
    id: "listing-1",
    title: "Trek Mountain Bike - Excellent Condition",
    description: "2022 Trek X-Caliber 8, lightly used with upgrades. Perfect for trails and commuting.",
    imageUrl: "https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=400&h=300&fit=crop",
    distanceMiles: 2.3,
    price: 1200,
    brand: "Trek",
    condition: "like-new",
    confidenceScore: 95,
    fraudStatus: "clear",
  },
  {
    id: "listing-2",
    title: "Giant Road Bike",
    description: "Giant Contend 3, great for road cycling. Minor scratches but mechanically sound.",
    imageUrl: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=400&h=300&fit=crop",
    distanceMiles: 5.7,
    price: 850,
    brand: "Giant",
    condition: "used",
    confidenceScore: 88,
    fraudStatus: "clear",
  },
  {
    id: "listing-3",
    title: "Specialized Electric Bike - Brand New",
    description: "Specialized Turbo Vado SL, still in box. Never ridden, unopened packaging.",
    imageUrl: "https://images.unsplash.com/photo-1571333250630-f0230c320b6d?w=400&h=300&fit=crop",
    distanceMiles: 8.2,
    price: 3500,
    brand: "Specialized",
    condition: "new",
    confidenceScore: 99,
    fraudStatus: "clear",
  },
  {
    id: "listing-4",
    title: "Cannondale Hybrid Bike",
    description: "Versatile hybrid bike, great for city and light trails. Well maintained.",
    imageUrl: "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=400&h=300&fit=crop",
    distanceMiles: 3.1,
    price: 650,
    brand: "Cannondale",
    condition: "like-new",
    confidenceScore: 92,
    fraudStatus: "clear",
  },
  {
    id: "listing-5",
    title: "Trek Cruiser - Comfortable Ride",
    description: "Classic cruiser style, perfect for beach rides and casual cycling.",
    imageUrl: "https://images.unsplash.com/photo-1559348349-86f1f65817fe?w=400&h=300&fit=crop",
    distanceMiles: 1.8,
    price: 450,
    brand: "Trek",
    condition: "used",
    confidenceScore: 85,
    fraudStatus: "clear",
  },
  {
    id: "listing-6",
    title: "Giant Mountain Bike - Trail Ready",
    description: "Giant Talon 2, suspension fork, disc brakes. Ready for serious trails.",
    imageUrl: "https://images.unsplash.com/photo-1511994298241-608e28f14fde?w=400&h=300&fit=crop",
    distanceMiles: 6.5,
    price: 980,
    brand: "Giant",
    condition: "like-new",
    confidenceScore: 90,
    fraudStatus: "clear",
  },
  {
    id: "listing-7",
    title: "Specialized Road Bike - Racing Edition",
    description: "Specialized Allez Sprint, carbon fiber components. Serious racing bike.",
    imageUrl: "https://images.unsplash.com/photo-1511994477422-b69e44bd4ea9?w=400&h=300&fit=crop",
    distanceMiles: 12.4,
    price: 2100,
    brand: "Specialized",
    condition: "like-new",
    confidenceScore: 93,
    fraudStatus: "clear",
  },
  {
    id: "listing-8",
    title: "Cannondale Kids Bike",
    description: "Perfect starter bike for kids 6-10 years old. Adjustable seat and training wheels included.",
    imageUrl: "https://images.unsplash.com/photo-1505705694340-019e1e335916?w=400&h=300&fit=crop",
    distanceMiles: 4.2,
    price: 280,
    brand: "Cannondale",
    condition: "used",
    confidenceScore: 87,
    fraudStatus: "clear",
  },
];

export const availableBrands = ["Trek", "Giant", "Specialized", "Cannondale"];

